#sorgular
# PUT  http://localhost:8080/v1/library/
# post http://localhost:8080/v1/library/
#GET http://localhost:8080/v1/library/2cad680f-942a-4e9d-bf70-aba6ca6f4ecc

#dakika 65 de kalındı



spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/v1/book/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/library/**
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


management:
  endpoint:
    web:
      exposure:
        include: "*"

